# Save as .codeclimate.yml (note leading .) in project root directory
languages:
    JavaScript: true
    PHP: true

engines:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php,inc,lib"
            standard: "PSR1,PSR2"
            ignore_warnings: true
    phpmd:
        enabled: true
        config:
            file_extensions: "php"
            rulesets: "unusedcode"
    csslint:
        enabled: true
    eslint:
        enabled: true

ratings:
    paths:
        - "**.php"

exclude_paths:
    - bin/*
    - var/*
    - build/*
    - src/**/*/Tests/*
    - src/**/*/Resources/config
    - vendor/*
    - web/config.php