language: php
sudo: false

env:
  global:
    - SYMFONY_VERSION=""

addons:
  code_climate:
    repo_token: c0878c1620cc24b05446192c5974072668acba14adb7bb694664ea06643caf1f

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x-dev"
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly
    - env: SYMFONY_VERSION="2.7.x-dev"
    - env: SYMFONY_VERSION="2.8.x-dev"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
  - composer install -n