language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - SYMFONY_ENV=test
  matrix:
    - DB=pgsql

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: c0878c1620cc24b05446192c5974072668acba14adb7bb694664ea06643caf1f


    - mysql

matrix:
  fast_finish: true
  exclude:
    - php: hhvm
      env: DB=pgsql
  allow_failures:
    - php: 7.0

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

after_script:
  - bin/test-reporter

install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install -n
  - bin/console cache:clear -e test
  - bin/console doctrine:database:create -e test
  - bin/console doctrine:schema:create -e test