api_artist:
    type: rest
    resource: Endo\ApiBundle\Controller\ArtistApiController

api_edition:
    type: rest
    resource: Endo\ApiBundle\Controller\EditionApiController

api_event:
    type: rest
    resource: Endo\ApiBundle\Controller\EventApiController

api_organizer:
    type: rest
    resource: Endo\ApiBundle\Controller\OrganizerApiController