Endo\DataBundle\Entity\Artist:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [api, id]
            since_version: 1.0.0
        name:
            expose: true
            type: string
            groups: [api]
            since_version: 1.0.0
        description:
            expose: true
            type: string
            groups: [api]
            since_version: 1.0.0
        events:
            expose: true
            type: ArrayCollection<Endo\DataBundle\Entity\Event>
            groups: [id]
            since_version: 1.0.0
