Endo\DataBundle\Entity\Edition:
    type: entity
    table: null
    repositoryClass: Endo\DataBundle\Repository\EditionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    oneToMany:
        events:
            targetEntity: Endo\DataBundle\Entity\Event
            mappedBy: edition
    lifecycleCallbacks: {  }
