Endo\DataBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: Endo\DataBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    manyToMany:
        artists:
            targetEntity: Endo\DataBundle\Entity\Artist
            inversedBy: events
    lifecycleCallbacks: {  }
