Endo\DataBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: Endo\DataBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: false
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                    fields:
                        - title
        isPublic:
            type: boolean
            nullable: false
        dateTimeStart:
            type: datetime
            nullable: false
        dateTimeEnd:
            type: datetime
            nullable: false
        description:
            type: text
            nullable: false
    manyToOne:
        edition:
            targetEntity: Endo\DataBundle\Entity\Edition
            inversedBy: events
    manyToMany:
        artists:
            targetEntity: Endo\DataBundle\Entity\Artist
            inversedBy: events
        organizers:
            targetEntity: Endo\DataBundle\Entity\Organizer
            inversedBy: events
        news:
            targetEntity: Endo\DataBundle\Entity\News
            mappedBy: events
    lifecycleCallbacks: {  }
