Endo\DataBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: Endo\DataBundle\Repository\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    manyToMany:
        events:
            targetEntity: Endo\DataBundle\Entity\Event
            inversedBy: news
        artists:
            targetEntity: Endo\DataBundle\Entity\Artist
            inversedBy: news
        organizers:
            targetEntity: Endo\DataBundle\Entity\Organizer
            inversedBy: news
    lifecycleCallbacks: {  }
