Endo\DataBundle\Entity\Organizer:
    type: entity
    table: null
    repositoryClass: Endo\DataBundle\Repository\OrganizerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
    manyToMany:
        events:
            targetEntity: Endo\DataBundle\Entity\Event
            mappedBy: organizers
        news:
            targetEntity: Endo\DataBundle\Entity\News
            mappedBy: organizers
    lifecycleCallbacks: {  }
